// This file was auto-generated by @joelek/autoguard. Edit at own risk.

import * as autoguard from "@joelek/autoguard/dist/lib-shared";

export const MailerOptions: autoguard.serialization.MessageGuard<MailerOptions> = autoguard.guards.Object.of({
	"hostname": autoguard.guards.String,
	"port": autoguard.guards.Number,
	"username": autoguard.guards.String,
	"password": autoguard.guards.String
}, {});

export type MailerOptions = autoguard.guards.Object<{
	"hostname": autoguard.guards.String,
	"port": autoguard.guards.Number,
	"username": autoguard.guards.String,
	"password": autoguard.guards.String
}, {}>;

export namespace Autoguard {
	export const Guards = {
		"MailerOptions": autoguard.guards.Reference.of(() => MailerOptions)
	};

	export type Guards = { [A in keyof typeof Guards]: ReturnType<typeof Guards[A]["as"]>; };

	export const Requests = {};

	export type Requests = { [A in keyof typeof Requests]: ReturnType<typeof Requests[A]["as"]>; };

	export const Responses = {};

	export type Responses = { [A in keyof typeof Responses]: ReturnType<typeof Responses[A]["as"]>; };
};
