// This file was auto-generated by @joelek/autoguard. Edit at own risk.

import * as autoguard from "@joelek/autoguard/dist/lib-shared";

export const MailerOptions: autoguard.serialization.MessageGuard<MailerOptions> = autoguard.guards.Object.of({
	"smtp": autoguard.guards.Object.of({
		"hostname": autoguard.guards.String,
		"port": autoguard.guards.Number,
		"username": autoguard.guards.String,
		"password": autoguard.guards.String
	}, {})
}, {
	"defaults": autoguard.guards.Object.of({}, {
		"to_address": autoguard.guards.String,
		"to_name": autoguard.guards.String,
		"from_address": autoguard.guards.String,
		"from_name": autoguard.guards.String,
		"reply_address": autoguard.guards.String,
		"reply_name": autoguard.guards.String
	})
});

export type MailerOptions = autoguard.guards.Object<{
	"smtp": autoguard.guards.Object<{
		"hostname": autoguard.guards.String,
		"port": autoguard.guards.Number,
		"username": autoguard.guards.String,
		"password": autoguard.guards.String
	}, {}>
}, {
	"defaults": autoguard.guards.Object<{}, {
		"to_address": autoguard.guards.String,
		"to_name": autoguard.guards.String,
		"from_address": autoguard.guards.String,
		"from_name": autoguard.guards.String,
		"reply_address": autoguard.guards.String,
		"reply_name": autoguard.guards.String
	}>
}>;

export namespace Autoguard {
	export const Guards = {
		"MailerOptions": autoguard.guards.Reference.of(() => MailerOptions)
	};

	export type Guards = { [A in keyof typeof Guards]: ReturnType<typeof Guards[A]["as"]>; };

	export const Requests = {};

	export type Requests = { [A in keyof typeof Requests]: ReturnType<typeof Requests[A]["as"]>; };

	export const Responses = {};

	export type Responses = { [A in keyof typeof Responses]: ReturnType<typeof Responses[A]["as"]>; };
};
