// This file was auto-generated by @joelek/autoguard. Edit at own risk.

import * as autoguard from "@joelek/autoguard/dist/lib-shared";
import { State } from "../../api/server";

export const UserProperties: autoguard.serialization.MessageGuard<UserProperties> = autoguard.guards.Object.of({
	"created_utc": autoguard.guards.Integer,
	"updated_utc": autoguard.guards.Integer,
	"email": autoguard.guards.String,
	"passdata": autoguard.guards.String
}, {
	"username": autoguard.guards.Union.of(
		autoguard.guards.String,
		autoguard.guards.Null
	)
});

export type UserProperties = autoguard.guards.Object<{
	"created_utc": autoguard.guards.Integer,
	"updated_utc": autoguard.guards.Integer,
	"email": autoguard.guards.String,
	"passdata": autoguard.guards.String
}, {
	"username": autoguard.guards.Union<[
		autoguard.guards.String,
		autoguard.guards.Null
	]>
}>;

export const RoleProperties: autoguard.serialization.MessageGuard<RoleProperties> = autoguard.guards.Object.of({
	"created_utc": autoguard.guards.Integer,
	"updated_utc": autoguard.guards.Integer,
	"name": autoguard.guards.String
}, {});

export type RoleProperties = autoguard.guards.Object<{
	"created_utc": autoguard.guards.Integer,
	"updated_utc": autoguard.guards.Integer,
	"name": autoguard.guards.String
}, {}>;

export const UserRoleProperties: autoguard.serialization.MessageGuard<UserRoleProperties> = autoguard.guards.Object.of({
	"created_utc": autoguard.guards.Integer,
	"updated_utc": autoguard.guards.Integer,
	"user_id": autoguard.guards.String,
	"role_id": autoguard.guards.String
}, {});

export type UserRoleProperties = autoguard.guards.Object<{
	"created_utc": autoguard.guards.Integer,
	"updated_utc": autoguard.guards.Integer,
	"user_id": autoguard.guards.String,
	"role_id": autoguard.guards.String
}, {}>;

export const SessionProperties: autoguard.serialization.MessageGuard<SessionProperties> = autoguard.guards.Intersection.of(
	autoguard.guards.Object.of({
		"created_utc": autoguard.guards.Integer,
		"updated_utc": autoguard.guards.Integer,
		"type": autoguard.guards.String,
		"reason": autoguard.guards.String,
		"expires_utc": autoguard.guards.Integer,
		"wait_until_utc": autoguard.guards.Integer
	}, {
		"username": autoguard.guards.Union.of(
			autoguard.guards.String,
			autoguard.guards.Null
		),
		"username_attempts": autoguard.guards.Union.of(
			autoguard.guards.Integer,
			autoguard.guards.Null
		),
		"email": autoguard.guards.Union.of(
			autoguard.guards.String,
			autoguard.guards.Null
		),
		"email_attempts": autoguard.guards.Union.of(
			autoguard.guards.Integer,
			autoguard.guards.Null
		),
		"code_hash": autoguard.guards.Union.of(
			autoguard.guards.String,
			autoguard.guards.Null
		),
		"code_hash_attempts": autoguard.guards.Union.of(
			autoguard.guards.Integer,
			autoguard.guards.Null
		),
		"passdata": autoguard.guards.Union.of(
			autoguard.guards.String,
			autoguard.guards.Null
		),
		"passdata_attempts": autoguard.guards.Union.of(
			autoguard.guards.Integer,
			autoguard.guards.Null
		),
		"authenticated_user_id": autoguard.guards.Union.of(
			autoguard.guards.String,
			autoguard.guards.Null
		),
		"ticket_hash": autoguard.guards.Union.of(
			autoguard.guards.String,
			autoguard.guards.Null
		)
	}),
	autoguard.guards.Reference.of(() => State)
);

export type SessionProperties = autoguard.guards.Intersection<[
	autoguard.guards.Object<{
		"created_utc": autoguard.guards.Integer,
		"updated_utc": autoguard.guards.Integer,
		"type": autoguard.guards.String,
		"reason": autoguard.guards.String,
		"expires_utc": autoguard.guards.Integer,
		"wait_until_utc": autoguard.guards.Integer
	}, {
		"username": autoguard.guards.Union<[
			autoguard.guards.String,
			autoguard.guards.Null
		]>,
		"username_attempts": autoguard.guards.Union<[
			autoguard.guards.Integer,
			autoguard.guards.Null
		]>,
		"email": autoguard.guards.Union<[
			autoguard.guards.String,
			autoguard.guards.Null
		]>,
		"email_attempts": autoguard.guards.Union<[
			autoguard.guards.Integer,
			autoguard.guards.Null
		]>,
		"code_hash": autoguard.guards.Union<[
			autoguard.guards.String,
			autoguard.guards.Null
		]>,
		"code_hash_attempts": autoguard.guards.Union<[
			autoguard.guards.Integer,
			autoguard.guards.Null
		]>,
		"passdata": autoguard.guards.Union<[
			autoguard.guards.String,
			autoguard.guards.Null
		]>,
		"passdata_attempts": autoguard.guards.Union<[
			autoguard.guards.Integer,
			autoguard.guards.Null
		]>,
		"authenticated_user_id": autoguard.guards.Union<[
			autoguard.guards.String,
			autoguard.guards.Null
		]>,
		"ticket_hash": autoguard.guards.Union<[
			autoguard.guards.String,
			autoguard.guards.Null
		]>
	}>,
	autoguard.guards.Reference<State>
]>;

export const OriginProperties: autoguard.serialization.MessageGuard<OriginProperties> = autoguard.guards.Object.of({
	"created_utc": autoguard.guards.Integer,
	"updated_utc": autoguard.guards.Integer,
	"address": autoguard.guards.String,
	"expires_utc": autoguard.guards.Integer,
	"wait_until_utc": autoguard.guards.Integer
}, {});

export type OriginProperties = autoguard.guards.Object<{
	"created_utc": autoguard.guards.Integer,
	"updated_utc": autoguard.guards.Integer,
	"address": autoguard.guards.String,
	"expires_utc": autoguard.guards.Integer,
	"wait_until_utc": autoguard.guards.Integer
}, {}>;

export const JobStatus: autoguard.serialization.MessageGuard<JobStatus> = autoguard.guards.Union.of(
	autoguard.guards.StringLiteral.of("ENQUEUED"),
	autoguard.guards.StringLiteral.of("RUNNING"),
	autoguard.guards.StringLiteral.of("SUCCESS"),
	autoguard.guards.StringLiteral.of("FAILURE")
);

export type JobStatus = autoguard.guards.Union<[
	autoguard.guards.StringLiteral<"ENQUEUED">,
	autoguard.guards.StringLiteral<"RUNNING">,
	autoguard.guards.StringLiteral<"SUCCESS">,
	autoguard.guards.StringLiteral<"FAILURE">
]>;

export const JobProperties: autoguard.serialization.MessageGuard<JobProperties> = autoguard.guards.Object.of({
	"created_utc": autoguard.guards.Integer,
	"updated_utc": autoguard.guards.Integer,
	"type": autoguard.guards.String,
	"status": autoguard.guards.Reference.of(() => JobStatus)
}, {
	"options": autoguard.guards.Union.of(
		autoguard.guards.String,
		autoguard.guards.Null
	),
	"description": autoguard.guards.Union.of(
		autoguard.guards.String,
		autoguard.guards.Null
	),
	"started_utc": autoguard.guards.Union.of(
		autoguard.guards.Integer,
		autoguard.guards.Null
	),
	"ended_utc": autoguard.guards.Union.of(
		autoguard.guards.Integer,
		autoguard.guards.Null
	),
	"expires_utc": autoguard.guards.Union.of(
		autoguard.guards.Integer,
		autoguard.guards.Null
	)
});

export type JobProperties = autoguard.guards.Object<{
	"created_utc": autoguard.guards.Integer,
	"updated_utc": autoguard.guards.Integer,
	"type": autoguard.guards.String,
	"status": autoguard.guards.Reference<JobStatus>
}, {
	"options": autoguard.guards.Union<[
		autoguard.guards.String,
		autoguard.guards.Null
	]>,
	"description": autoguard.guards.Union<[
		autoguard.guards.String,
		autoguard.guards.Null
	]>,
	"started_utc": autoguard.guards.Union<[
		autoguard.guards.Integer,
		autoguard.guards.Null
	]>,
	"ended_utc": autoguard.guards.Union<[
		autoguard.guards.Integer,
		autoguard.guards.Null
	]>,
	"expires_utc": autoguard.guards.Union<[
		autoguard.guards.Integer,
		autoguard.guards.Null
	]>
}>;

export namespace Autoguard {
	export const Guards = {
		"UserProperties": autoguard.guards.Reference.of(() => UserProperties),
		"RoleProperties": autoguard.guards.Reference.of(() => RoleProperties),
		"UserRoleProperties": autoguard.guards.Reference.of(() => UserRoleProperties),
		"SessionProperties": autoguard.guards.Reference.of(() => SessionProperties),
		"OriginProperties": autoguard.guards.Reference.of(() => OriginProperties),
		"JobStatus": autoguard.guards.Reference.of(() => JobStatus),
		"JobProperties": autoguard.guards.Reference.of(() => JobProperties)
	};

	export type Guards = { [A in keyof typeof Guards]: ReturnType<typeof Guards[A]["as"]>; };

	export const Requests = {};

	export type Requests = { [A in keyof typeof Requests]: ReturnType<typeof Requests[A]["as"]>; };

	export const Responses = {};

	export type Responses = { [A in keyof typeof Responses]: ReturnType<typeof Responses[A]["as"]>; };
};
