// This file was auto-generated by @joelek/autoguard. Edit at own risk.

import * as autoguard from "@joelek/autoguard/dist/lib-shared";
import { State } from "../../api";

export const UserProperties: autoguard.serialization.MessageGuard<UserProperties> = autoguard.guards.Object.of({
	"email": autoguard.guards.String,
	"passdata": autoguard.guards.String
}, {
	"username": autoguard.guards.String
});

export type UserProperties = autoguard.guards.Object<{
	"email": autoguard.guards.String,
	"passdata": autoguard.guards.String
}, {
	"username": autoguard.guards.String
}>;

export const SessionProperties: autoguard.serialization.MessageGuard<SessionProperties> = autoguard.guards.Intersection.of(
	autoguard.guards.Reference.of(() => State),
	autoguard.guards.Object.of({
		"expires_utc": autoguard.guards.Integer,
		"wait_until_utc": autoguard.guards.Integer
	}, {
		"username": autoguard.guards.String,
		"email": autoguard.guards.String,
		"token_hash": autoguard.guards.String,
		"passdata": autoguard.guards.String,
		"user_id": autoguard.guards.String,
		"ticket_hash": autoguard.guards.String
	})
);

export type SessionProperties = autoguard.guards.Intersection<[
	autoguard.guards.Reference<State>,
	autoguard.guards.Object<{
		"expires_utc": autoguard.guards.Integer,
		"wait_until_utc": autoguard.guards.Integer
	}, {
		"username": autoguard.guards.String,
		"email": autoguard.guards.String,
		"token_hash": autoguard.guards.String,
		"passdata": autoguard.guards.String,
		"user_id": autoguard.guards.String,
		"ticket_hash": autoguard.guards.String
	}>
]>;

export const OriginProperties: autoguard.serialization.MessageGuard<OriginProperties> = autoguard.guards.Object.of({
	"address": autoguard.guards.String,
	"wait_until_utc": autoguard.guards.Integer
}, {});

export type OriginProperties = autoguard.guards.Object<{
	"address": autoguard.guards.String,
	"wait_until_utc": autoguard.guards.Integer
}, {}>;

export namespace Autoguard {
	export const Guards = {
		"UserProperties": autoguard.guards.Reference.of(() => UserProperties),
		"SessionProperties": autoguard.guards.Reference.of(() => SessionProperties),
		"OriginProperties": autoguard.guards.Reference.of(() => OriginProperties)
	};

	export type Guards = { [A in keyof typeof Guards]: ReturnType<typeof Guards[A]["as"]>; };

	export const Requests = {};

	export type Requests = { [A in keyof typeof Requests]: ReturnType<typeof Requests[A]["as"]>; };

	export const Responses = {};

	export type Responses = { [A in keyof typeof Responses]: ReturnType<typeof Responses[A]["as"]>; };
};
